apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: testnodejs
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/xinjiang/testnodejs0516:6a416b8bfc1b8597d627ec5f97056421ef8fb7d7@sha256:3fd1598c8e8e7486c928c0733e483d4fb597ca86553ed40b12198483b675421a
        name: container-image  
